# Generated by Django 3.2.6 on 2022-02-16 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='User',
        ),
    ]
