# Generated by Django 3.2.6 on 2022-02-17 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_rename_model_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip',
            field=models.IntegerField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
