# Generated by Django 3.2.6 on 2022-02-17 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_auto_20220217_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zip',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
